### ISSUE TITLE
The PSMs in psm.tsv from MSFragger have already been filtered with 1% PSM and protein FDR by default. There is no need to filter with PeptideProphet probability again

### ISSUE THREAD

**Issue by fcyu** [PayneLab/SingleCellBenchMark#1]
Thanks for your benchmarking excellent benchmarking! After checking the psm.tsv, I think MSFragger's result is not filtered correctly.

By default, the PSMs in psm.tsv are filtered with 1% PSM and 1% protein FDR. But your psm.tsv seems from no FDR filtering (the minimum probability is 0.0501). I guess you set 100% FDR in runn Philosopher's filter command and wanted to filter the PSMs by yourself. A better way to have a fair comparison in Figure 1 is by skipping running ProteinProphet (to disable protein FDR filtering), and using the default options in Philosopher's filter command.

Please feel free to contact me if there are any questions.

Best,

Fengchao

**Comment by samuelpayne** [comment]
I think I understand what you're saying. but not totally sure. We did not filter PSMs prior to rescoring with mokapot. it is best for mokapot to have ample examples of true and false PSMs, so it can run a better optimization.
