### ISSUE TITLE
The latest MSFragger generates pin files which is for Percolator analysis

### ISSUE THREAD

**Issue by fcyu** [PayneLab/SingleCellBenchMark#2]
Thanks for your benchmarking using Percolator/Mokapot.

I am not sure what MSFragger version you are using, but the latest version has the ability to generate pin files (by setting `output_format = pepXML_pin`) for Percolator/Mokapot. I suggest you use that file rather than create the file by yourself.

Best,

Fengchao

**Comment by samuelpayne** [comment]
Yeah. I saw that release after we had finished analyses and were ready to submit. We can use the pin file for analysis in the re-submission.
